### ISSUE TITLE
bintray shutdown

### ISSUE THREAD

**Issue by namreeb** [egor-tensin/build-boost#1]
Per their messages to the boost mailing list, the bintray mirror for downloading boost source has been shutdown as of yesterday.  The URLs on the boost website now go to https://boostorg.jfrog.io/ (e.g. https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.7z)

**Comment by egor-tensin** [comment]
Thanks! I thinks this still used to work thanks to using sourceforge as backup, but I switched from Bintray to jfrog.io as well.
