### ISSUE TITLE
Does not seem to work with CMake find_package

### ISSUE THREAD

**Issue by MichaelVoelkel** [egor-tensin/build-boost#2]
Hi,

thanks a lot for your great action!

So, it seems that CMake cannot really use this with find_package. The output dir has nice libs with clear names, but find_package creates different output lib file names... Is this known? I could just hard-code the filenames, of course, but it's not just as nice and would not work outside of GitHub Actions.

**Comment by MichaelVoelkel** [comment]
Hi again.

Sorry, I was wrong here. find_package worked but Boost wanted to link lib filenames itself, which is not compatible.

But I was able to fix with:

`target_compile_definitions(my_project PRIVATE -DBOOST_ALL_NO_LIB)`

Now, the project only links against what is passed via `target_link_libraries` and this works fine.

Thanks again for your great package!

**Comment by egor-tensin** [comment]
@MichaelVoelkel Thanks, that's a great point. I got so used to doing

```
target_link_libraries(target PRIVATE Boost::disable_autolinking)
# I think this is pretty much equivalent to doing `-DBOOST_ALL_NO_LIB`
```

that I routinely forget this might be an issue. In my defense, the auto-linking feature of Boost is IMO _extremely_ faulty and regularly bites me in the ass. I'll look into this.

**Comment by MichaelVoelkel** [comment]
Yeah, I totally agree with the auto-linking feature. I still see it as Boost's fault, not yours.
