### ISSUE TITLE
Support for vs2022 and msvc143

### ISSUE THREAD

**Issue by GoobyCorp** [egor-tensin/build-boost#4]
Is this a planned addition? If I specify windows-2022 and use MSVC 14.3 I just get this error:
`boost-build: error: argument --toolset: invalid Visual Studio version: 2022`

**Comment by egor-tensin** [comment]
Yes, this will be implemented till tomorrow.

**Comment by egor-tensin** [comment]
Done. See for example a test run: https://github.com/egor-tensin/build-boost/actions/runs/1658641305 (the windows-2022 jobs). Boost 1.78.0 is the oldest version to support VS 2022 though.
