### ISSUE TITLE
 Build Boost for C#

### ISSUE THREAD

**Issue by adityagi54** [egor-tensin/build-boost#5]
I want to use Boost Libraries in C#. Is it possible and how can I achieve that?

**Comment by LucaLush** [comment]
You may try to compile boost library as a DLL then use c# to call the functions in this dll

**Comment by egor-tensin** [comment]
Sorry, I was in no fit state to deal with my GitHub Actions for the past year. I'll try to keep up in the future.

Replaying just for the sake of completeness. Boost libraries are C++ libraries. I'm sure there's a way to use C++ libraries from C#, but I don't know what that way would be of the top of my head.
